-- Add per_side_weight column to exercises table
-- This replaces the flawed is_unilateral-based /SIDE logic.
-- per_side_weight = true means the exercise uses two separate weights simultaneously
-- (e.g., two dumbbells, two kettlebells, two cable handles).
-- The user enters weight for ONE side and volume is calculated as weight × 2 × reps.

ALTER TABLE exercises ADD COLUMN IF NOT EXISTS per_side_weight BOOLEAN DEFAULT false;

UPDATE exercises SET per_side_weight = true
WHERE name IN (
    'Alternate Hammer Curl',
    'Alternate Incline Dumbbell Curl',
    'Arnold Dumbbell Press',
    'Around The Worlds',
    'Bent Over Dumbbell Rear Delt Raise With Head On Bench',
    'Bent Over Low-Pulley Side Lateral',
    'Bent Over Two-Dumbbell Row',
    'Bent Over Two-Dumbbell Row With Palms In',
    'Cable Chest Press',
    'Cable Crossover',
    'Cable Iron Cross',
    'Cable Rear Delt Fly',
    'Cable Seated Lateral Raise',
    'Cable Shoulder Press',
    'Cable Shrugs',
    'Close-Grip Dumbbell Press',
    'Cuban Press',
    'Decline Dumbbell Bench Press',
    'Decline Dumbbell Flyes',
    'Decline Dumbbell Triceps Extension',
    'Double Kettlebell Jerk',
    'Double Kettlebell Push Press',
    'Double Kettlebell Snatch',
    'Double Kettlebell Windmill',
    'Dumbbell Alternate Bicep Curl',
    'Dumbbell Bench Press',
    'Dumbbell Bench Press with Neutral Grip',
    'Dumbbell Bicep Curl',
    'Dumbbell Clean',
    'Dumbbell Floor Press',
    'Dumbbell Flyes',
    'Dumbbell Incline Row',
    'Dumbbell Incline Shoulder Raise',
    'Dumbbell Lunges',
    'Dumbbell Lying Pronation',
    'Dumbbell Lying Rear Lateral Raise',
    'Dumbbell Lying Supination',
    'Dumbbell Prone Incline Curl',
    'Dumbbell Raise',
    'Dumbbell Rear Lunge',
    'Dumbbell Scaption',
    'Dumbbell Shoulder Press',
    'Dumbbell Shrug',
    'Dumbbell Squat',
    'Dumbbell Squat To A Bench',
    'Dumbbell Step Ups',
    'Dumbbell Tricep Extension -Pronated Grip',
    'External Rotation',
    'Flat Bench Cable Flyes',
    'Flexor Incline Dumbbell Curls',
    'Front Dumbbell Raise',
    'Front Incline Dumbbell Raise',
    'Front Squats With Two Kettlebells',
    'Front Two-Dumbbell Raise',
    'Hammer Curls',
    'Hammer Grip Incline DB Bench Press',
    'High Cable Curls',
    'Incline Cable Chest Press',
    'Incline Cable Flye',
    'Incline Dumbbell Bench With Palms Facing In',
    'Incline Dumbbell Curl',
    'Incline Dumbbell Flyes',
    'Incline Dumbbell Flyes - With A Twist',
    'Incline Dumbbell Press',
    'Incline Hammer Curls',
    'Incline Inner Biceps Curl',
    'Iron Cross',
    'Low Cable Crossover',
    'Lying Dumbbell Tricep Extension',
    'Lying Rear Delt Raise',
    'Lying Supine Dumbbell Curl',
    'Middle Back Shrug',
    'Overhead Cable Curl',
    'Palms-Down Dumbbell Wrist Curl Over A Bench',
    'Palms-Up Dumbbell Wrist Curl Over A Bench',
    'Power Partials',
    'Preacher Hammer Dumbbell Curl',
    'Reverse Flyes',
    'Reverse Flyes With External Rotation',
    'Seated Bent-Over Rear Delt Raise',
    'Seated Bent-Over Two-Arm Dumbbell Triceps Extension',
    'Seated Cable Shoulder Press',
    'Seated Dumbbell Curl',
    'Seated Dumbbell Inner Biceps Curl',
    'Seated Dumbbell Palms-Down Wrist Curl',
    'Seated Dumbbell Palms-Up Wrist Curl',
    'Seated Dumbbell Press',
    'Seated Side Lateral Raise',
    'Side Lateral Raise',
    'Side Laterals to Front Raise',
    'Split Squat with Dumbbells',
    'Standing Bent-Over Two-Arm Dumbbell Triceps Extension',
    'Standing Cable Chest Press',
    'Standing Dumbbell Calf Raise',
    'Standing Dumbbell Press',
    'Standing Dumbbell Reverse Curl',
    'Standing Dumbbell Straight-Arm Front Delt Raise Above Head',
    'Standing Dumbbell Upright Row',
    'Standing Inner-Biceps Curl',
    'Standing Low-Pulley Deltoid Raise',
    'Standing Palms-In Dumbbell Press',
    'Stiff-Legged Dumbbell Deadlift',
    'Tate Press',
    'Tricep Dumbbell Kickback',
    'Two-Arm Dumbbell Preacher Curl',
    'Two-Arm Kettlebell Clean',
    'Two-Arm Kettlebell Jerk',
    'Two-Arm Kettlebell Military Press',
    'Two-Arm Kettlebell Row',
    'Zottman Curl',
    'Zottman Preacher Curl'
);
